# -*- coding: utf-8 -*-
"""A_H_Extraction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11hx_rO9uNo6PsT3P6N-0SnYQ-vFdWcBZ
"""

!pip install mne mne-bids

from google.colab import drive
drive.mount('/content/drive')

import mne
from mne_bids import BIDSPath, read_raw_bids
import re

bids_root = "/content/drive/MyDrive/ieeg_ieds_bids"
bids_path = BIDSPath(
    subject='02',
    task='sleep',
    datatype='ieeg',
    root=bids_root
)

import re
import mne

raw = read_raw_bids(bids_path, verbose=False) #loading raw data

all_chs = raw.ch_names

amyg_prefixes = ["LA", "RA", "LBAA", "RBAA"]           # left/right amygdala
hipp_prefixes = [
    "LH", "RH",
    "LAH", "RAH",
    "LMH", "RMH",
    "LPHG", "RPHG"]   # left/right hippocampus

def is_valid_contact(ch_name, prefixes):  #checks whether the channel name is one of the amygdala/hippocampus prefixes
    if "-" in ch_name:  #exclude all bipolar channels, monopolar contacts 1-4 (signals recorded from one electrode contact)
        return False

    for p in prefixes: #loops through each valid prefix region (LA, RA, LMH, RMH)
        if re.fullmatch(fr"{p}[1-4]$", ch_name):  #uses regular expresstion to match channel names
            return True
    return False

#loops through all channels and keeps only if above function is true AND the prefix matches the labels

amyg_channels = [ch for ch in all_chs if is_valid_contact(ch, amyg_prefixes)]
hipp_channels = [ch for ch in all_chs if is_valid_contact(ch, hipp_prefixes)]

# Combine
selected_channels = amyg_channels + hipp_channels

raw_selected = raw.copy().pick(selected_channels)

print("Amygdala channels:", amyg_channels)
print("Hippocampus channels:", hipp_channels)
print("Final selected channels:", selected_channels)
print("Shape:", raw_selected.get_data().shape)

